# the first stage of our build will extract the layers
FROM amazoncorretto:17.0.2 as builder
WORKDIR app
COPY . .

ARG MAVEN_VERSION=3.8.6
ARG GH_TOKEN
ARG GH_USERNAME
ENV GITHUB_TOKEN=${GH_TOKEN}
ENV GITHUB_USERNAME=${GH_USERNAME}

# we need cache for this step
# also it is multistage build and this image ll be discarded. Only artifact copied
RUN yum update -y && yum install -y install libxml2-devel libxslt-devel tar which gzip && \
  rm -rf /var/cache/yum/* && \
  yum clean all && \
  mkdir -p /usr/share/maven /usr/share/maven/ref && \
  curl -fsSL -o /tmp/apache-maven.tar.gz https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
  tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 && \
  rm -f /tmp/apache-maven.tar.gz && \
  ln -s /usr/share/maven/bin/mvn /usr/bin/mvn 

RUN  mvn clean package -s settings.xml -Dskip.unit.tests=true && \
   version=$(xmllint --xpath "/*[name()='project']/*[name()='version']/text()" pom.xml) && \
   name=$(xmllint --xpath "/*[name()='project']/*[name()='name']/text()" pom.xml) && \
   echo $name:$version && \
   mv target/$name-$version.jar target/app.jar


FROM amazoncorretto:17.0.2-alpine
COPY --from=builder app/target/*.jar ./
COPY docker/resources/logback-json.xml ./

EXPOSE 8080
ENTRYPOINT ["java","-Dlogging.config=/logback-json.xml","-jar","/app.jar"]

